package common;

public enum Event {
    FIRST_START, SECOND_START,
    FIRST_EN_WORD, SECOND_EN_WORD,
    RU_WORD, WRONG_TOPIC, CHANGE_TOPIC,
    HINT, TRY, HELP, STATISTIC, EXIT, NONE,
    STAT_STR, WRONG,
    ADD_WORD_VOCABULARY, ADD_VOCABULARY, END_VOCABULARY,
    EDIT_TRANSLATE
}
